name: e2e full suite
on: pull_request
jobs:
  wait-for-calypso-live:
    name: Wait for Calypso.live
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check external author
        run: |
              if [[ ! -z $CIRCLE_PR_USERNAME ]]; then
                echo 'PRs from external authors cannot run on calypso.live'
                exit 1
              fi
      #npm -v- name: Wait for calypso.live build
        #if: github.event_name == 'pull_request' && ( github.event.action == 'labeled' || github.event.action == 'synchronize' ) && contains( github.event.pull_request.labels.*.name, '[Status] Needs e2e Testing' )
        #env:
        #  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        #run: ./test/e2e/scripts/wait-for-running-branch.sh
  e2e-full-suite-desktop:
    name: e2e Full Suite - Desktop
    runs-on: ubuntu-latest
    needs: wait-for-calypso-live
    container:
      image: circleci/node:10.16.3-browsers
      env:
        NODE_CONFIG_ENV: test
        BRANCHNAME: $GITHUB_REF
        TEST_VIDEO: true
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - name: Install npm deps
        run: cd test/e2e && npm ci
      - name: Decrypt Config
        env:
          CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
        run: cd test/e2e && npm run decryptconfig
      - name: Run Tests
        run: cd test/e2e && ./run.sh -R -g -s desktop -S ${{ github.event.pull_request.head.sha }}
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: screenshots
          path: ./test/e2e/screenshots
  e2e-full-suite-mobile:
    name: e2e Full Suite - Mobile
    runs-on: ubuntu-latest
    needs: wait-for-calypso-live
    container:
      image: circleci/node:10.16.3-browsers
      env:
        NODE_CONFIG_ENV: test
        BRANCHNAME: $GITHUB_REF
        TEST_VIDEO: true
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - name: Install npm deps
        run: cd test/e2e && npm ci
      - name: Decrypt Config
        env:
          CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
        run: cd test/e2e && npm run decryptconfig
      - name: Run Tests
        run: cd test/e2e && ./run.sh -R -g -s mobile -S ${{ github.event.pull_request.head.sha }}
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: screenshots
          path: ./test/e2e/screenshots

